config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials:
      - id: orviz-github-basic
        username_var: GIT_USER
        password_var: GIT_PASSWORD
      - id: k8s_synergy_bot_rsa
        username_var: SSH_USER
        keyfile_var: SSH_KEYFILE
        #passphrase_var: SSH_PASSPHRASE
      - type: file
        id: k8s_synergy_cluster
        variable: KUBECONFIG

sqa_criteria:
  SvcQC.Dep:
    repos:
      kubectl:
        container: kubectl
        commands:
          - /examples/scripts/create_kustomization
          - |
            #!/usr/bin/env bash
            ssh -qND 6443 -i ${SSH_KEYFILE} -o ProxyCommand="ssh -i ${SSH_KEYFILE} -W %h:%p ${SSH_USER}@194.210.120.36" ${SSH_USER}@10.0.0.67 &
            SSH_PID="$!"
            kubectl apply -k /examples
            if ! kubectl rollout status deployment wordpress --timeout 3600s; then
              kubectl rollout undo deployment wordpress
              kubectl rollout status deployment wordpress
              exit 1
            fi

#environment:
  #JPL_DOCKERPUSH: "kubectl"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: 45

#timeout: 1200