config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials:
      - id: orviz-github-basic
        username_var: GIT_USER
        password_var: GIT_PASSWORD
      - id: k8s_synergy_bot_rsa
        username_var: SSH_USER
        keyfile_var: SSH_KEYFILE
        #passphrase_var: SSH_PASSPHRASE
      - type: file
        id: k8s_synergy_cluster
        variable: KUBECONFIG
      - id: k8s_synergy_cluster_bastion
        variable: BASTION_NODE
      - id: k8s_synergy_cluster_master
        variable: MASTER_NODE

sqa_criteria:
  SvcQC.Dep:
    repos:
      kubectl:
        container: kubectl
        commands:
          - /examples/scripts/create_kustomization
          - /examples/scripts/deploy_wordpress

environment:
  SOCKS_TUNNEL_PORT: 38080
  K8S_API_PORT: 6443
  KUBECTL_ROLLOUT_TIMEOUT: "300s"
  #JPL_DOCKERPUSH: "kubectl"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: "45"

#timeout: 1200