version: "3"

services:
  kubectl:
    build:
      context: "./.sqa/"
      dockerfile: "./Dockerfile"
      cache_from:
        - "bitnami/kubectl:1.23"
    image: "eosc-synergy/kubectl:1.23"
    container_name: "kubectl"
    hostname: "kubectl"
    volumes:
     - ./:/examples
    entrypoint: [ sleep, infinity ]
