version: "3"

services:
  kubectl:
    #environment:
    #  - KUBECONFIG
    #  - SSH_KEYFILE
    #  - SSH_USER
    build:
      context: "./.sqa/"
      dockerfile: "./Dockerfile"
      #cache_from:
      #  - "bitnami/kubectl:1.23"
    image: "eosc-synergy/kubectl:1.23"
    container_name: "kubectl"
    hostname: "kubectl"
    volumes:
     - ./:/examples
     - /jenkins/workspace:/jenkins/workspace
    entrypoint: [ sleep, infinity ]
