version: "3"

services:
  kubectl:
    environment:
      - SOCKS_TUNNEL_PORT
      - K8S_API_PORT
      - KUBECTL_ROLLOUT_TIMEOUT
    build:
      context: "./.sqa/"
      dockerfile: "./Dockerfile"
      #cache_from:
      #  - "bitnami/kubectl:1.23"
    image: "eosc-synergy/kubectl:1.23"
    container_name: "kubectl"
    hostname: "kubectl"
    volumes:
     - ./:/examples
     - /jenkins/workspace:/jenkins/workspace
    entrypoint: [ sleep, infinity ]
