version: "3"

services:
  kubectl:
    environment:
      - SSH_KEYFILE
      - SSH_USER
      - KUBECONFIG
    build:
      context: "./.sqa/"
      dockerfile: "./Dockerfile"
      #cache_from:
      #  - "bitnami/kubectl:1.23"
    image: "eosc-synergy/kubectl:1.23"
    container_name: "kubectl"
    hostname: "kubectl"
    volumes:
     - ./:/examples
     - "${SSH_KEYFILE}"
     - "${KUBECONFIG}"

    entrypoint: [ sleep, infinity ]
