#!/usr/bin/env bash

cat <<EOF >>/examples/kustomization.yaml
secretGenerator:
- name: mysql-pass
  literals:
  - password=YOUR_PASSWORD

resources:
    - mysql-wordpress-pd/mysql-deployment.yaml
    - mysql-wordpress-pd/wordpress-deployment.yaml

EOF
