#!/usr/bin/env bash

mkdir -p /root/.ssh
chmod 700 /root/.ssh
ssh-keyscan -H ${BASTION_NODE} > /root/.ssh/known_hosts
chmod 600 /root/.ssh/known_hosts

echo ""
echo "Open ssh socks tunnel to kubernetes master node"
echo ""
ssh -qND ${SOCKS_TUNNEL_PORT} -i ${SSH_KEYFILE} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/root/.ssh/known_hosts -o ProxyCommand="ssh -i ${SSH_KEYFILE} -W %h:%p ${SSH_USER}@${BASTION_NODE}" ${SSH_USER}@${MASTER_NODE} &
SSH_EXIT="$?"
SSH_PID="$!"
if [[ "x${SSH_PID}" == "x" || "x${SSH_EXIT}" == "x" || ${SSH_EXIT} != 0 ]]; then
    echo "ssh socks tunnel failed with error code: ${SSH_EXIT}"
    exit 1;
fi
echo "ssh socks tunnel created with success:"

echo ""
echo "Test access to the kubernetes API"
echo ""
sleep 5
K8S_API_STATUS_CODE=$(https_proxy=socks5h://localhost:${SOCKS_TUNNEL_PORT} curl -k -v --write-out %{http_code} --silent --output /dev/null https://localhost:${K8S_API_PORT}/api)
if [[ "x${K8S_API_STATUS_CODE}" == "x" || ${K8S_API_STATUS_CODE} != 403 ]]; then
    echo "curl to kubernetes api failed with error code: ${K8S_API_STATUS_CODE}"
    kill ${SSH_PID}
    exit 1;
fi

echo ""
echo "Deploy kubernetes infrastructure"
echo ""
kubectl --insecure-skip-tls-verify apply -k /examples
if ! kubectl --insecure-skip-tls-verify rollout status deployment wordpress --timeout ${KUBECTL_ROLLOUT_TIMEOUT}; then
    echo "Someting went wrong!.. undo the current rollout and rollback to the previous revision."
    kubectl --insecure-skip-tls-verify rollout undo deployment wordpress
    kubectl --insecure-skip-tls-verify rollout status deployment wordpress --timeout ${KUBECTL_ROLLOUT_TIMEOUT}
    kubectl --insecure-skip-tls-verify delete -k /examples
    kill ${SSH_PID}
    exit 1
fi

echo ""
echo "### Deployment finished successfuly"
echo ""
kubectl --insecure-skip-tls-verify describe -k /examples

echo ""
echo "### Delete the deployment"
echo ""
kubectl --insecure-skip-tls-verify delete -k /examples

kill ${SSH_PID}
